openapi: 3.1.0
info:
  title: Asana Allocations Projects API
  description: The Asana Allocations API allows users to manage and allocate resources within their Asana project management system. An allocation object represents how much of a resource (e.g. person, team) is dedicated to a specific work object (e.g. project, portfolio) over a specific period of time. The effort value can be a percentage or number of hours.
  version: '1.0'
  termsOfService: https://asana.com/terms
  contact:
    name: Asana Support
    url: https://asana.com/support
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://app.asana.com/api/1.0
  description: Main endpoint.
security:
- personalAccessToken: []
- oauth2: []
tags:
- name: Projects
  description: 'A project represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. A project exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions.


    Projects in organizations are shared with a single team. Currently, the team of a project cannot be changed via the API. Non-organization workspaces do not have teams and so you should not specify the team of project in a regular workspace.


    Followers of a project are a subset of the members of that project. Followers of a project will receive all updates including tasks created, added and removed from that project. Members of the project have access to and will receive status updates of the project. Adding followers to a project will add them as members if they are not already, removing followers from a project will not affect membership.


    **Note:** You can use certain project endpoints to operate on [user task lists](/reference/user-task-lists) ([My Tasks](https://asana.com/guide/help/fundamentals/my-tasks)) by substituting the `{project_gid}` with the `{user_task_list_gid}`. For example, you can perform operations on the custom fields of a user task list by using the following projects endpoints: [Add a custom field to a project](/reference/addcustomfieldsettingforproject), [Remove a custom field from a project](/reference/r[...]'
paths:
  /projects:
    get:
      summary: Asana Get multiple projects
      description: 'Returns the compact project records for some filtered set of projects. Use one or more of the parameters provided to filter the projects returned.

        *Note: This endpoint may timeout for large domains. Try filtering by team!*'
      tags:
      - Projects
      operationId: getProjects
      security:
      - oauth2:
        - projects:read
    post:
      summary: Asana Create a project
      description: 'Create a new project in a workspace or team.


        Every project is required to be created in a specific workspace or

        organization, and this cannot be changed once set. Note that you can use

        the `workspace` parameter regardless of whether or not it is an

        organization.


        If the workspace for your project is an organization, you must also

        supply a `team` to share the project with.


        Returns the full record of the newly created project.'
      tags:
      - Projects
      operationId: createProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}:
    get:
      summary: Asana Get a project
      description: Returns the complete project record for a single project.
      tags:
      - Projects
      operationId: getProject
      security:
      - oauth2:
        - projects:read
    put:
      summary: Asana Update a project
      description: 'A specific, existing project can be updated by making a PUT request on

        the URL for that project. Only the fields provided in the `data` block

        will be updated; any unspecified fields will remain unchanged.


        When using this method, it is best to specify only those fields you wish

        to change, or else you may overwrite changes made by another user since

        you last retrieved the task.


        Returns the complete updated project record.'
      tags:
      - Projects
      operationId: updateProject
      security:
      - oauth2:
        - projects:write
    delete:
      summary: Asana Delete a project
      description: 'A specific, existing project can be deleted by making a DELETE request on

        the URL for that project.


        Returns an empty data record.'
      tags:
      - Projects
      operationId: deleteProject
      security:
      - oauth2:
        - projects:delete
  /projects/{project_gid}/duplicate:
    post:
      summary: Asana Duplicate a project
      description: Creates and returns a job that will asynchronously handle the duplication.
      tags:
      - Projects
      operationId: duplicateProject
      security:
      - oauth2:
        - projects:write
  /tasks/{task_gid}/projects:
    get:
      summary: Asana Get projects a task is in
      description: Returns a compact representation of all of the projects the task is in.
      tags:
      - Projects
      operationId: getProjectsForTask
      security:
      - oauth2:
        - projects:read
  /teams/{team_gid}/projects:
    get:
      summary: Asana Get a team's projects
      description: Returns the compact project records for all projects in the team.
      tags:
      - Projects
      operationId: getProjectsForTeam
      security:
      - oauth2:
        - projects:read
    post:
      summary: Asana Create a project in a team
      description: 'Creates a project shared with the given team.


        Returns the full record of the newly created project.'
      tags:
      - Projects
      operationId: createProjectForTeam
      security:
      - oauth2:
        - projects:write
  /workspaces/{workspace_gid}/projects:
    get:
      summary: Asana Get all projects in a workspace
      description: 'Returns the compact project records for all projects in the workspace.

        *Note: This endpoint may timeout for large domains. Prefer the `/teams/{team_gid}/projects` endpoint.*'
      tags:
      - Projects
      operationId: getProjectsForWorkspace
      security:
      - oauth2:
        - projects:read
    post:
      summary: Asana Create a project in a workspace
      description: 'Creates a project in the workspace.


        If the workspace for your project is an organization, you must also

        supply a team to share the project with.


        Returns the full record of the newly created project.'
      tags:
      - Projects
      operationId: createProjectForWorkspace
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/addCustomFieldSetting:
    post:
      summary: Asana Add a custom field to a project
      description: Custom fields are associated with projects by way of custom field settings.  This method creates a setting for the project.
      tags:
      - Projects
      operationId: addCustomFieldSettingForProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/removeCustomFieldSetting:
    post:
      summary: Asana Remove a custom field from a project
      description: Removes a custom field setting from a project.
      tags:
      - Projects
      operationId: removeCustomFieldSettingForProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/task_counts:
    get:
      summary: Asana Get task count of a project
      description: 'Get an object that holds task count fields. **All fields are excluded by default**. You must [opt in](/docs/inputoutput-options) using `opt_fields` to get any information from this endpoint.


        This endpoint has an additional [rate limit](/docs/rate-limits) and each field counts especially high against our [cost limits](/docs/rate-limits#cost-limits).


        Milestones are just tasks, so they are included in the `num_tasks`, `num_incomplete_tasks`, and `num_completed_tasks` counts.'
      tags:
      - Projects
      operationId: getTaskCountsForProject
      security:
      - oauth2:
        - projects:read
  /projects/{project_gid}/addMembers:
    post:
      summary: Asana Add users to a project
      description: 'Adds the specified list of users as members of the project. Note that a user being added as a member may also be added as a *follower* as a result of this operation. This is because the user''s default notification settings (i.e., in the "Notifications" tab of "My Profile Settings") will override this endpoint''s default behavior of setting "Tasks added" notifications to `false`.

        Returns the updated project record.'
      tags:
      - Projects
      operationId: addMembersForProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/removeMembers:
    post:
      summary: Asana Remove users from a project
      description: 'Removes the specified list of users from members of the project.

        Returns the updated project record.'
      tags:
      - Projects
      operationId: removeMembersForProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/addFollowers:
    post:
      summary: Asana Add followers to a project
      description: 'Adds the specified list of users as followers to the project. Followers are a subset of members who have opted in to receive "tasks added" notifications for a project. Therefore, if the users are not already members of the project, they will also become members as a result of this operation.

        Returns the updated project record.'
      tags:
      - Projects
      operationId: addFollowersForProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/removeFollowers:
    post:
      summary: Asana Remove followers from a project
      description: 'Removes the specified list of users from following the project, this will not affect project membership status.

        Returns the updated project record.'
      tags:
      - Projects
      operationId: removeFollowersForProject
      security:
      - oauth2:
        - projects:write
  /projects/{project_gid}/saveAsTemplate:
    post:
      summary: Asana Create a project template from a project
      description: Creates and returns a job that will asynchronously handle the project template creation.
      tags:
      - Projects
      operationId: projectSaveAsTemplate
components:
  securitySchemes:
    personalAccessToken:
      type: http
      description: A personal access token for the Asana API.
      scheme: bearer
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: https://app.asana.com/-/oauth_authorize
          tokenUrl: https://app.asana.com/-/oauth_token
          scopes:
            default: Provides access to all endpoints documented in the API reference.
