openapi: 3.1.0
info:
  title: Asana Allocations Tasks API
  description: The Asana Allocations API allows users to manage and allocate resources within their Asana project management system. An allocation object represents how much of a resource (e.g. person, team) is dedicated to a specific work object (e.g. project, portfolio) over a specific period of time. The effort value can be a percentage or number of hours.
  version: '1.0'
  termsOfService: https://asana.com/terms
  contact:
    name: Asana Support
    url: https://asana.com/support
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://app.asana.com/api/1.0
  description: Main endpoint.
security:
- personalAccessToken: []
- oauth2: []
tags:
- name: Tasks
  description: 'The task is the basic object around which many operations in Asana are centered. In the Asana application, multiple tasks populate the middle pane according to some view parameters, and the set of selected tasks determines the more detailed information presented in the details pane.


    Sections are unique in that they will be included in the `memberships` field of task objects returned in the API when the task is within a section. They can also be used to manipulate the ordering of a task within a project.


    [Queries](/reference/gettasks) return a [compact representation of each task object](/reference/tasks). To retrieve *all* fields or *specific set* of the fields, use [field selectors](/docs/inputoutput-options) to manipulate what data is included in a response.'
paths:
  /tasks/{task_gid}/tags:
    get:
      summary: Asana Get a task's tags
      description: Get a compact representation of all of the tags the task has.
      tags:
      - Tasks
      operationId: getTagsForTask
  /tasks:
    get:
      summary: Asana Get multiple tasks
      description: 'Returns the compact task records for some filtered set of tasks. Use one or more of the parameters provided to filter the tasks returned. You must specify a `project` or `tag` if you do not specify `assignee` and `workspace`.


        For more complex task retrieval, use [workspaces/{workspace_gid}/tasks/search](/reference/searchtasksforworkspace).'
      tags:
      - Tasks
      operationId: getTasks
      security:
      - oauth2:
        - tasks:read
    post:
      summary: Asana Create a task
      description: 'Creating a new task is as easy as POSTing to the `/tasks` endpoint with a

        data block containing the fields you’d like to set on the task. Any

        unspecified fields will take on default values.


        Every task is required to be created in a specific workspace, and this

        workspace cannot be changed once set. The workspace need not be set

        explicitly if you specify `projects` or a `parent` task instead.'
      tags:
      - Tasks
      operationId: createTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}:
    get:
      summary: Asana Get a task
      description: Returns the complete task record for a single task.
      tags:
      - Tasks
      operationId: getTask
      security:
      - oauth2:
        - tasks:read
    put:
      summary: Asana Update a task
      description: 'A specific, existing task can be updated by making a PUT request on the

        URL for that task. Only the fields provided in the `data` block will be

        updated; any unspecified fields will remain unchanged.


        When using this method, it is best to specify only those fields you wish

        to change, or else you may overwrite changes made by another user since

        you last retrieved the task.


        Returns the complete updated task record.'
      tags:
      - Tasks
      operationId: updateTask
      security:
      - oauth2:
        - tasks:write
    delete:
      summary: Asana Delete a task
      description: 'A specific, existing task can be deleted by making a DELETE request on

        the URL for that task. Deleted tasks go into the “trash” of the user

        making the delete request. Tasks can be recovered from the trash within a

        period of 30 days; afterward they are completely removed from the system.


        Returns an empty data record.'
      tags:
      - Tasks
      operationId: deleteTask
      security:
      - oauth2:
        - tasks:delete
  /tasks/{task_gid}/duplicate:
    post:
      summary: Asana Duplicate a task
      description: Creates and returns a job that will asynchronously handle the duplication.
      tags:
      - Tasks
      operationId: duplicateTask
      security:
      - oauth2:
        - tasks:write
  /projects/{project_gid}/tasks:
    get:
      summary: Asana Get tasks from a project
      description: Returns the compact task records for all tasks within the given project, ordered by their priority within the project. Tasks can exist in more than one project at a time.
      tags:
      - Tasks
      operationId: getTasksForProject
      security:
      - oauth2:
        - tasks:read
  /sections/{section_gid}/tasks:
    get:
      summary: Asana Get tasks from a section
      description: '*Board view only*: Returns the compact section records for all tasks within the given section.'
      tags:
      - Tasks
      operationId: getTasksForSection
      security:
      - oauth2:
        - tasks:read
  /tags/{tag_gid}/tasks:
    get:
      summary: Asana Get tasks from a tag
      description: Returns the compact task records for all tasks with the given tag. Tasks can have more than one tag at a time.
      tags:
      - Tasks
      operationId: getTasksForTag
      security:
      - oauth2:
        - tasks:read
  /user_task_lists/{user_task_list_gid}/tasks:
    get:
      summary: Asana Get tasks from a user task list
      description: 'Returns the compact list of tasks in a user’s My Tasks list.

        *Note: Access control is enforced for this endpoint as with all Asana API endpoints, meaning a user’s private tasks will be filtered out if the API-authenticated user does not have access to them.*

        *Note: Both complete and incomplete tasks are returned by default unless they are filtered out (for example, setting `completed_since=now` will return only incomplete tasks, which is the default view for “My Tasks” in Asana.)*'
      tags:
      - Tasks
      operationId: getTasksForUserTaskList
      security:
      - oauth2:
        - tasks:read
  /tasks/{task_gid}/subtasks:
    get:
      summary: Asana Get subtasks from a task
      description: Returns a compact representation of all of the subtasks of a task.
      tags:
      - Tasks
      operationId: getSubtasksForTask
      security:
      - oauth2:
        - tasks:read
    post:
      summary: Asana Create a subtask
      description: Creates a new subtask and adds it to the parent task. Returns the full record for the newly created subtask.
      tags:
      - Tasks
      operationId: createSubtaskForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/setParent:
    post:
      summary: Asana Set the parent of a task
      description: parent, or no parent task at all. Returns an empty data block. When using `insert_before` and `insert_after`, at most one of those two options can be specified, and they must already be subtasks of the parent.
      tags:
      - Tasks
      operationId: setParentForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/dependencies:
    get:
      summary: Asana Get dependencies from a task
      description: Returns the compact representations of all of the dependencies of a task.
      tags:
      - Tasks
      operationId: getDependenciesForTask
      security:
      - oauth2:
        - tasks:read
  /tasks/{task_gid}/addDependencies:
    post:
      summary: Asana Set dependencies for a task
      description: Marks a set of tasks as dependencies of this task, if they are not already dependencies. *A task can have at most 30 dependents and dependencies combined*.
      tags:
      - Tasks
      operationId: addDependenciesForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/removeDependencies:
    post:
      summary: Asana Unlink dependencies from a task
      description: Unlinks a set of dependencies from this task.
      tags:
      - Tasks
      operationId: removeDependenciesForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/dependents:
    get:
      summary: Asana Get dependents from a task
      description: Returns the compact representations of all of the dependents of a task.
      tags:
      - Tasks
      operationId: getDependentsForTask
      security:
      - oauth2:
        - tasks:read
  /tasks/{task_gid}/addDependents:
    post:
      summary: Asana Set dependents for a task
      description: Marks a set of tasks as dependents of this task, if they are not already dependents. *A task can have at most 30 dependents and dependencies combined*.
      tags:
      - Tasks
      operationId: addDependentsForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/removeDependents:
    post:
      summary: Asana Unlink dependents from a task
      description: Unlinks a set of dependents from this task.
      tags:
      - Tasks
      operationId: removeDependentsForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/addProject:
    post:
      summary: Asana Add a project to a task
      description: 'Adds the task to the specified project, in the optional location

        specified. If no location arguments are given, the task will be added to

        the end of the project.


        `addProject` can also be used to reorder a task within a project or

        section that already contains it.


        At most one of `insert_before`, `insert_after`, or `section` should be

        specified. Inserting into a section in an non-order-dependent way can be

        done by specifying section, otherwise, to insert within a section in a

        particular place, specify `insert_before` or `insert_after` and a task

        within the section to anchor the position of this task.


        A task can have at most 20 projects multi-homed to it.


        Returns an empty data block.'
      tags:
      - Tasks
      operationId: addProjectForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/removeProject:
    post:
      summary: Asana Remove a project from a task
      description: 'Removes the task from the specified project. The task will still exist in

        the system, but it will not be in the project anymore.


        Returns an empty data block.'
      tags:
      - Tasks
      operationId: removeProjectForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/addTag:
    post:
      summary: Asana Add a tag to a task
      description: Adds a tag to a task. Returns an empty data block.
      tags:
      - Tasks
      operationId: addTagForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/removeTag:
    post:
      summary: Asana Remove a tag from a task
      description: Removes a tag from a task. Returns an empty data block.
      tags:
      - Tasks
      operationId: removeTagForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/addFollowers:
    post:
      summary: Asana Add followers to a task
      description: 'Adds followers to a task. Returns an empty data block.

        Each task can be associated with zero or more followers in the system.

        Requests to add/remove followers, if successful, will return the complete updated task record, described above.'
      tags:
      - Tasks
      operationId: addFollowersForTask
      security:
      - oauth2:
        - tasks:write
  /tasks/{task_gid}/removeFollowers:
    post:
      summary: Asana Remove followers from a task
      description: Removes each of the specified followers from the task if they are following. Returns the complete, updated record for the affected task.
      tags:
      - Tasks
      operationId: removeFollowerForTask
      security:
      - oauth2:
        - tasks:write
  /workspaces/{workspace_gid}/tasks/custom_id/{custom_id}:
    get:
      summary: Asana Get a task for a given custom ID
      description: Returns a task given a custom ID shortcode.
      tags:
      - Tasks
      operationId: getTaskForCustomID
      security:
      - oauth2:
        - tasks:read
  /workspaces/{workspace_gid}/tasks/search:
    get:
      summary: Asana Search tasks in a workspace
      description: 'To mirror the functionality of the Asana web app''s advanced search feature, the Asana API has a task search endpoint that allows you to build complex filters to find and retrieve the exact data you need.

        #### Premium access

        Like the Asana web product''s advance search feature, this search endpoint will only be available to premium Asana users. A user is premium if any of the following is true:


        - The workspace in which the search is being performed is a premium workspace - The user is a member of a premium team inside the workspace


        Even if a user is only a member of a premium team inside a non-premium workspace, search will allow them to find data anywhere in the workspace, not just inside the premium team. Making a search request using credentials of a non-premium user will result in a `402 Payment Required` error.

        #### Pagination

        Search results are not stable; repeating the same query multiple times may return the data in a different order, even if the data do not change. Because of this, the traditional [pagination](https://developers.asana.com/docs/#pagination) available elsewhere in the Asana API is not available here. However, you can paginate manually by sorting the search results by their creation time and then modifying each subsequent query to exclude data you have already seen. Page sizes are limited to [...]

        #### Eventual consistency

        Changes in Asana (regardless of whether they’re made though the web product or the API) are forwarded to our search infrastructure to be indexed. This process can take between 10 and 60 seconds to complete under normal operation, and longer during some production incidents. Making a change to a task that would alter its presence in a particular search query will not be reflected immediately. This is also true of the advanced search feature in the web product.

        #### Rate limits

        You may receive a `429 Too Many Requests` response if you hit any of our [rate limits](https://developers.asana.com/docs/#rate-limits).

        #### Custom field parameters

        | Parameter name | Custom field type | Accepted type |

        |---|---|---|

        | custom_fields.{gid}.is_set | All | Boolean |

        | custom_fields.{gid}.value | Text | String |

        | custom_fields.{gid}.value | Number | Number |

        | custom_fields.{gid}.value | Enum | Enum option ID |

        | custom_fields.{gid}.starts_with | Text only | String |

        | custom_fields.{gid}.ends_with | Text only | String |

        | custom_fields.{gid}.contains | Text only | String |

        | custom_fields.{gid}.less_than | Number only | Number |

        | custom_fields.{gid}.greater_than | Number only | Number |



        For example, if the gid of the custom field is 12345, these query parameter to find tasks where it is set would be `custom_fields.12345.is_set=true`. To match an exact value for an enum custom field, use the gid of the desired enum option and not the name of the enum option: `custom_fields.12345.value=67890`.


        **Not Supported**: searching for multiple exact matches of a custom field, searching for multi-enum custom field


        *Note: If you specify `projects.any` and `sections.any`, you will receive tasks for the project **and** tasks for the section. If you''re looking for only tasks in a section, omit the `projects.any` from the request.*'
      tags:
      - Tasks
      operationId: searchTasksForWorkspace
      security:
      - oauth2:
        - tasks:read
components:
  securitySchemes:
    personalAccessToken:
      type: http
      description: A personal access token for the Asana API.
      scheme: bearer
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: https://app.asana.com/-/oauth_authorize
          tokenUrl: https://app.asana.com/-/oauth_token
          scopes:
            default: Provides access to all endpoints documented in the API reference.
